INSERT INTO products (product_name, category, brand, price ) VALUES
('Coca-Cola Classic', 'Drink', 'Coca-Cola', 2.50),
('Pepsi', 'Drink', 'Pepsi', 2.40),
('Orange Juice', 'Drink', 'Tropicana', 3.20),
('Mineral Water', 'Drink', 'Evian', 1.80),
('Green Tea', 'Drink', 'Lipton', 2.00),
('Espresso Coffee', 'Drink', 'Nespresso', 3.50),
('Energy Drink', 'Drink', 'Red Bull', 3.75),
('Milk Chocolate Bar', 'Food', 'Nestlé', 1.50),
('Potato Chips', 'Food', 'Lays', 2.90),
('Cheddar Cheese', 'Food', 'Kraft', 4.60),
('White Bread', 'Food', 'Wonder', 2.30),
('Whole Wheat Pasta', 'Food', 'Barilla', 2.80),
('Tomato Ketchup', 'Food', 'Heinz', 3.40),
('Strawberry Yogurt', 'Food', 'Danone', 1.20),
('Vanilla Ice Cream', 'Food', 'Haagen-Dazs', 6.50),
('Frozen Pizza', 'Food', 'Dr. Oetker', 5.90),
('Chicken Nuggets', 'Food', 'McCain', 6.20),
('Breakfast Cereal', 'Food', 'Kellogg''s', 4.10),
('Peanut Butter', 'Food', 'Skippy', 3.80),
('Dark Chocolate', 'Food', 'Lindt', 3.60);